//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MovieRatingModel : DbContext
    {
        public MovieRatingModel()
            : base("name=MovieRatingModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Poster> Poster { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<Rating> Rating { get; set; }
        public virtual DbSet<Movie> Movie { get; set; }
    }
}
