//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movie
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Cover { get; set; }
        public string Director { get; set; }
        public string Writers { get; set; }
        public string Actor { get; set; }
        public string Types { get; set; }
        public string Area { get; set; }
        public string Languages { get; set; }
        public string Show { get; set; }
        public string Long { get; set; }
        public string Abstract { get; set; }
        public string Stills0 { get; set; }
        public string Stills1 { get; set; }
        public string Stills2 { get; set; }
        public string Stills3 { get; set; }
        public string Stills4 { get; set; }
        public bool Valid { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
        public string CreateBy { get; set; }
        public Nullable<decimal> Averige { get; set; }
    }
}
