//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rating
    {
        public int ID { get; set; }
        public int Movie { get; set; }
        public int Score { get; set; }
        public string Comment { get; set; }
        public int Praise { get; set; }
        public System.DateTime Dated { get; set; }
        public int Users { get; set; }
    
        public virtual Users UserInfo { get; set; }
    }
}
